version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: networkmonitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./back-end
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/networkmonitor
      REDIS_URL: redis://redis:6379/0

  celery_worker:
    build: ./back-end
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - backend
      - redis
      - db
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/networkmonitor
      REDIS_URL: redis://redis:6379/0


volumes:
  postgres_data:
